title: HelpHQ
description: >- # this means to ignore newlines until "baseurl:"
  HelpHQ is a powerful help center app for Shopify. It's designed to
  reduce support email and look great on any theme.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://help-hq.com" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown

collections:
  docs:
    output: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
